name: CI Mysql with Data.sql

on:
  push:
    branches:
      - inacio@feat/mysql-connection

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Unit Tests
        run: docker run --rm -v "$PWD":/app -w /app maven:3.6-openjdk-17 mvn clean test

      - name: Log in to Docker Hub
        if: success()
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        if: success()
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/mystock-backend-mysql:latest .

      - name: Push Docker image
        if: success()
        run: docker push ${{ secrets.DOCKER_USERNAME }}/mystock-backend-mysql:latest
